# Generated by Django 3.1.1 on 2020-10-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
