# Generated by Django 3.1.1 on 2020-10-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='test',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
    ]
