# Generated by Django 3.1.1 on 2020-10-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='test',
        ),
    ]
