# Generated by Django 3.1.1 on 2020-10-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20201009_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
