# Generated by Django 3.1.1 on 2020-10-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
